#!/bin/bash
# Journal key Claude Code actions to DEV_JOURNAL.md
# This hook runs after tool executions to track development progress

set -e

JOURNAL_FILE="${CLAUDE_WORKING_DIRECTORY}/DEV_JOURNAL.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

# Read hook input from stdin
INPUT=$(cat)

# Extract tool name and details from JSON input
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"')
TOOL_INPUT=$(echo "$INPUT" | jq -r '.tool_input // {}')

# Only journal significant actions
case "$TOOL_NAME" in
    Write|Edit)
        FILE_PATH=$(echo "$TOOL_INPUT" | jq -r '.file_path // "unknown"')
        # Get just the filename for brevity
        FILENAME=$(basename "$FILE_PATH")
        ACTION="Modified \`$FILENAME\`"
        ;;
    Bash)
        COMMAND=$(echo "$TOOL_INPUT" | jq -r '.command // ""' | head -c 80)
        # Only log significant bash commands (builds, tests, installs)
        if [[ "$COMMAND" =~ ^(xcodebuild|swift|swiftlint|brew|git\ commit|git\ push) ]]; then
            ACTION="Ran: \`${COMMAND}\`"
        else
            exit 0  # Skip non-significant commands
        fi
        ;;
    Task)
        DESCRIPTION=$(echo "$TOOL_INPUT" | jq -r '.description // "task"')
        ACTION="Task: $DESCRIPTION"
        ;;
    *)
        exit 0  # Skip other tools
        ;;
esac

# Create journal file with header if it doesn't exist
if [ ! -f "$JOURNAL_FILE" ]; then
    cat > "$JOURNAL_FILE" << 'EOF'
# Development Journal

This file tracks key development actions performed by Claude Code.
Auto-generated by `.claude/hooks/journal-action.sh`

---

EOF
fi

# Append the journal entry
echo "- **[$TIMESTAMP]** $ACTION" >> "$JOURNAL_FILE"
