disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing

included:
  - HCDInterviewCoach

excluded:
  - Pods
  - .build

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20
